### PR TITLE
New math, plus script to download latex images of equations

### PR DESCRIPTION
**Pull request by DLu**
Extension of #37 with additional explanation of the equation/derivations. CC: @EwingKang 

[Formatted README](https://github.com/locusrobotics/robot_navigation/blob/15fed7253dd79a2371bb764756413244bf172ddb/dlux_global_planner/README.md)

[Formatted Derivation](https://github.com/locusrobotics/robot_navigation/blob/4a88d9b21a544d6171256d4d49473287cc021003/dlux_global_planner/Derivation.md)

### CODE REVIEW

**Comment by EwingKang** [comment]
So, to figure out where the numbers came from, I have tested 2 additional points.
Historic numbers:  
C0=0.7040; C1=0.5307; C2=-0.2301
-------------------------------------------------
Delta=0 (by @DLu )
C0=0.7071; C1=0.5; C2=-0.1768
-------------------------------------------------
Delta = 1/2
C0=0.7019; C1=0.5270; C2=-0.2160
-------------------------------------------------
Delta = 1
C0=0.875; C1=0.5; C2=-0.25
(7/8);     (1/2);      -1/4
-------------------------------------------------

**Comment by DLu** [comment]
I'm not sure where the difference is, but I'm not getting the same values as you for the coefficients. Can you check out [this plot](https://www.desmos.com/calculator/jmtcqocpxu) and see if it makes sense to you.

**Comment by EwingKang** [comment]
Hello, @DLu 
To my understanding in Taylor series expansion, you have to multiply the "difference between variable and expansion point" after the coefficient. This is also the case mentioned in the [formatted derivation](https://github.com/locusrobotics/robot_navigation/blob/15fed7253dd79a2371bb764756413244bf172ddb/dlux_global_planner/Derivation.md). 

In the case of expansion at [d]=0, it is a special case that the coefficient of the nth-order [d] is actually nth-order derivative of the function (times 1/n!). 

It could be I'm wrong somewhere, hope this math make sense to you:
IMAG0849

**Comment by DLu** [comment]
@EwingKang - You're right...thanks for keeping me honest. I've updated the PR with the general equations for the different Taylor Series. The historical values are now pretty close to `a=0.5`. Also, what I've calculated for the coefficients matches what you have for delta=0.5, but not delta=1.0 (which is off by a factor of 2).

**Comment by EwingKang** [comment]
@DLu  I've re-calculate delta=1 and you are right, it should be: 
C2= -0.5, C1=1, C0=1/2
as the new readme listed. 
I see no further issue regarding the math portion of the document. :smiley: 
Thank you (especially for your patient) !!!

**Pull request merged**
